version: '3.1'

services:
  mysql:
    container_name: mysql_docker
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123Demo@456
    ports:
      - 3306:3306
    volumes:
      - ./docker:/var/lib/mysql

  adminer:
    container_name: adminer_docker
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mysql: